spring:
 application:
    name: northwind
 profiles:
      active: local
 datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://127.0.0.1:1433;database=Northwind;loginTimeout=30;
      username: WebClient1
      password: 123_Stella
      
 data:
  mongodb:
    repositories:
      enabled: true
    database: Northwind
    uri: mongodb://mongoadmin:123Mongo@127.0.0.1:28017/?authSource=admin&authMechanism=SCRAM-SHA-1
          
    
############################################################  
 APPID: c025ef7501012873d99a30b78a7d2920
 weather_service_url: https://api.openweathermap.org/data/2.5/forecast
 ############################################################
 
logging:
  level:
    root: INFO
    com.northwind.northwind: DEBUG
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    