spring:
 application:
    name: northwind
 profiles:
      active: local
 datasource:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://127.0.0.1:1433;databaseName=Notherwind;integratedSecurity=true;
      username: WebClient
      password: 340$Uuxwp7Mcxo7Khy
      
 data:
  mongodb:
    repositories:
      enabled: true
    database: Northwind
    uri: mongodb://mongoadmin:123Mongo@127.0.0.1:28017/?authSource=admin&authMechanism=SCRAM-SHA-1
          
logging:
  level:
    root: INFO
    com.northwind.northwind: DEBUG
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE    